### ISSUE TITLE
Паутина?

### ISSUE THREAD

**Issue by bzaar** [Koziev/NLP_Datasets#1]
https://github.com/Koziev/NLP_Datasets/blob/master/Lemmas/Data/lemma2normal.dat#L59

**Comment by bzaar** [comment]
Также в этой строке ошибка:
https://github.com/Koziev/NLP_Datasets/blob/master/Lemmas/Data/lemma2normal.dat#L161

**Comment by Koziev** [comment]
> https://github.com/Koziev/NLP_Datasets/blob/master/Lemmas/Data/lemma2normal.dat#L59
> https://github.com/Koziev/NLP_Datasets/blob/master/Lemmas/Data/lemma2normal.dat#L161
Спасибо за замечания, исправил в lemma2normal.dat.
Исправления в исходный тезаурус грамматического словаря запланировал.
